blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView

app_name = BlogConfig.name

urlpatterns = [
    path('blog_create', BlogCreateView.as_view(), name='blog_create'),
    path('blog_list', BlogListView.as_view(), name='blog_list'),
    path('blog_detail/<int:pk>', BlogDetailView.as_view(), name='blog_detail')
]

mailing_list/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mailing_list.apps import MailingListConfig
from mailing_list.views import ClientCreateView, MessageCreateView, MailingSettingsCreateView, HomeView, ClientListView, \
    ClientDetailView, ClientDeleteView, MessageListView, MessageDetailView, MessageDeleteView, MailingSettingsListView, \
    MailingSettingsDetailView, MailingSettingsDeleteView, ClientUpdateView, MailingAttemptDetailView, MailingPauseView, \
    StatisticView

app_name = MailingListConfig.name
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('client_create', ClientCreateView.as_view(), name='client_create'),
    path('message_create', MessageCreateView.as_view(), name='message_create'),
    path('mailingsettings_create', MailingSettingsCreateView.as_view(), name='mailingsettings_create'),

    path('client_list', ClientListView.as_view(), name='client_list'),
    path('client_detail/<int:pk>', ClientDetailView.as_view(), name='client_detail'),
    path('client_detail/<int:pk>/delete', ClientDeleteView.as_view(), name='client_delete'),
    path('client_detail/<int:pk>/update', ClientUpdateView.as_view(), name='client_update'),

    path('message_list', MessageListView.as_view(), name='message_list'),
    path('message_detail/<int:pk>', MessageDetailView.as_view(), name='message_detail'),
    path('message_detail/<int:pk>/delete', MessageDeleteView.as_view(), name='message_delete'),
    path('mailingsettings_list', MailingSettingsListView.as_view(), name='mailingsettings_list'),
    path('mailingsettings_detail/<int:pk>', MailingSettingsDetailView.as_view(), name='mailingsettings_detail'),
    path('mailingsettings_detail/<int:pk>/delete', MailingSettingsDeleteView.as_view(), name='mailingsettings_delete'),
    path('mailingsettings_detail/attempt/<str:slug>', MailingAttemptDetailView.as_view(), name='mailingsettings_attempt'),
    path('mailing_pause/<int:pk>', MailingPauseView.as_view(), name='mailing_pause'),
    path('statistic/', StatisticView.as_view(), name='statistic'),

]

scheduler_email/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from scheduler_email import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('mailing_list.urls', namespace='mailing_list')),
                  path('', include('users.urls', namespace='users')),
                  path('blog/', include('blog.urls', namespace='blog'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from django.views.decorators.cache import cache_page

from users.apps import UsersConfig
from users.forms import LoginForm
from users.views import UserRegisterView, UserInputSecretKey, UserListView, UserDeactivateView

app_name = UsersConfig.name

urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='user_register'),
    path('login/', LoginView.as_view(template_name='users/user_login.html', form_class=LoginForm), name='user_login'),
    path('logout/', LogoutView.as_view(), name='user_logout'),
    path('user_verify/<int:pk>', UserInputSecretKey.as_view(), name='user_verify'),
    path('user_list', UserListView.as_view(), name='user_list'),
    path('user_deactivate/<int:pk>', UserDeactivateView.as_view(), name='user_deactivate'),
]

mailing_list/models.py
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import post_save
from slugify import slugify

from scheduler_email.settings import AUTH_USER_MODEL
from users.models import User

NULLABLE = {'blank': True, 'null': True}


class Client(models.Model):
    mail = models.EmailField(max_length=100, verbose_name='почта')
    fullname = models.CharField(max_length=200, verbose_name='полное имя')
    comment = models.TextField(verbose_name='комментарий')
    owner = models.ForeignKey(AUTH_USER_MODEL, default=True, on_delete=models.CASCADE, to_field='id', verbose_name='Пользователь', **NULLABLE)

    def __str__(self):
        return self.fullname

    class Meta:
        verbose_name = 'клиент'
        verbose_name_plural = 'клиенты'


class Message(models.Model):
    title_message = models.CharField(max_length=200, verbose_name='тема письма')
    body_message = models.TextField(verbose_name='тело письма')
    owner = models.ForeignKey(AUTH_USER_MODEL, default=True, on_delete=models.CASCADE, to_field='id', verbose_name='Пользователь', **NULLABLE)

    def __str__(self):
        return self.title_message

    class Meta:
        verbose_name = 'сообщение для рассылки'
        verbose_name_plural = 'сообщения для рассылки'


class MailingSettings(models.Model):
    title = models.CharField(max_length=200, default='', verbose_name='Название рассылки')
    first_sending_date = models.DateTimeField(verbose_name='дата и время первой отправки рассылки')
    period = models.PositiveSmallIntegerField(verbose_name='периодичность')
    mailing_status = models.CharField(default=False, choices=[
        ('created', 'Создана'),
        ('running', 'Активна'),
        ('completed', 'Завершена')], verbose_name='статус')
    message = models.ForeignKey(Message, default=None, on_delete=models.CASCADE, to_field='id',
                                verbose_name='сообщение')
    client = models.ManyToManyField(Client, default=None, related_name='mailing', verbose_name='клиент')
    owner = models.ForeignKey(AUTH_USER_MODEL, default=True, related_name='mailing', on_delete=models.CASCADE, to_field='id', verbose_name='Пользователь', **NULLABLE)

    # day='*/10' → каждые 10 дней

    def __str__(self):
        return f'{self.first_sending_date, self.period, self.mailing_status}'

    class Meta:
        verbose_name = 'настройка рассылки'
        verbose_name_plural = 'настройки рассылки'


class MailingAttempt(models.Model):
    mailing = models.OneToOneField(MailingSettings, default=False, on_delete=models.CASCADE, related_name='log',
                                   verbose_name='рассылка')
    slug = models.SlugField(max_length=200, unique=True, blank=True, verbose_name='URL slug')
    last_attempt_date = models.DateTimeField(**NULLABLE, verbose_name='дата и время последней попытки')
    attempt_status = models.BooleanField(**NULLABLE, default=False, verbose_name='статус попытки')
    mail_service_response = models.TextField(**NULLABLE, default=None, verbose_name='ответ почтового сервиса')
    owner = models.ForeignKey(AUTH_USER_MODEL, default=True, on_delete=models.CASCADE, to_field='id', verbose_name='Пользователь', **NULLABLE)

    def __str__(self):
        return f'{self.attempt_status}, {self.last_attempt_date}, {self.mail_service_response}'

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.mailing.title)
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'попытка рассылки'
        verbose_name_plural = 'попытки рассылки'


@receiver(post_save, sender=MailingSettings)
def create_mailing_log(sender, instance, created, **kwargs):
    if created:
        MailingAttempt.objects.create(mailing=instance, owner=instance.owner)

mailing_list/forms.py
from django import forms

from mailing_list.models import Client, Message, MailingSettings


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ClientForm(StyleFormMixin, forms.ModelForm ):
    class Meta:
        model = Client
        fields = '__all__'

class MessageForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Message
        fields = '__all__'

class MailingSettingsForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = MailingSettings
        fields = ('title', 'first_sending_date', 'period', 'mailing_status', 'message', 'client')

mailing_list/views.py
from apscheduler.triggers.cron import CronTrigger
from apscheduler.triggers.interval import IntervalTrigger
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import ListView, CreateView, TemplateView, DetailView, DeleteView, UpdateView
from django_apscheduler.models import DjangoJobExecution, DjangoJob

from blog.models import Blog
from mailing_list.forms import ClientForm, MessageForm, MailingSettingsForm
from mailing_list.management.commands.logger import logger
from mailing_list.models import Client, Message, MailingSettings, MailingAttempt
from dj_scheduler import scheduler, send_email_to_clients
from mailing_list.services import get_cached_queryset


class SelfUserPassesTestMixin(UserPassesTestMixin):
    """Чтобы придерживаться принципа DRY"""
    raise_exception = True

    def test_func(self):
        return self.request.user.is_superuser or self.get_object().owner == self.request.user


class HomeView(LoginRequiredMixin, TemplateView):
    template_name = 'mailing_list/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['blog_list'] = Blog.objects.order_by('-publish_date')[:3]
        return context


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mailing_list:client_list')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class ClientListView(LoginRequiredMixin, ListView):
    model = Client

    def get_queryset(self):
        print(self.request.user.pk)
        return get_cached_queryset(self.request.user, Client)


class ClientDetailView(LoginRequiredMixin, SelfUserPassesTestMixin, DetailView):
    model = Client


class ClientDeleteView(LoginRequiredMixin, SelfUserPassesTestMixin, DeleteView):
    model = Client
    success_url = reverse_lazy('mailing_list:client_list')


class ClientUpdateView(LoginRequiredMixin, SelfUserPassesTestMixin, UpdateView):
    model = Client
    form_class = ClientForm

    def get_success_url(self):
        return reverse('mailing_list:client_detail', kwargs={'pk': self.object.pk})


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('mailing_list:message_list')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class MessageListView(LoginRequiredMixin, ListView):
    model = Message

    def get_queryset(self):
        return get_cached_queryset(self.request.user, Message)


class MessageDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = Message
    raise_exception = True

    def test_func(self):
        return self.request.user.is_staff or self.get_object().owner == self.request.user


class MessageDeleteView(LoginRequiredMixin, SelfUserPassesTestMixin, DeleteView):
    model = Message
    success_url = reverse_lazy('mailing_list:message_list')


class MailingSettingsCreateView(LoginRequiredMixin, CreateView):
    model = MailingSettings
    form_class = MailingSettingsForm
    success_url = reverse_lazy('mailing_list:mailingsettings_list')

    def form_valid(self, form):
        if form.is_valid():
            form.instance.owner = self.request.user
            mailing_settings = form.save()
            logger.info(f'{mailing_settings.first_sending_date}')
            scheduler.add_job(
                send_email_to_clients,
                trigger=IntervalTrigger(days=mailing_settings.period,
                                        start_date=mailing_settings.first_sending_date),
                id=f'send_email_{mailing_settings.id}',
                max_instances=1,
                replace_existing=True,

                kwargs={'message_id': mailing_settings.message.id, 'mailing_id': mailing_settings.id}
            )
            logger.info('джоба добавлена')
            mailing_settings.save()
        return super().form_valid(form)


class MailingSettingsListView(LoginRequiredMixin, ListView):
    model = MailingSettings

    def get_queryset(self):
        return get_cached_queryset(self.request.user, MailingSettings)


class MailingSettingsDeleteView(LoginRequiredMixin, SelfUserPassesTestMixin, DeleteView):
    model = MailingSettings

    def get_success_url(self):
        scheduler.remove_job(f'send_email_{self.object.pk}')
        return reverse_lazy('mailing_list:mailingsettings_list')


class MailingAttemptDetailView(LoginRequiredMixin, SelfUserPassesTestMixin, DetailView):
    model = MailingAttempt
    slug_field = 'slug'
    slug_url_kwarg = 'slug'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['job'] = [job for job in DjangoJob.objects.all() if job.id[-1:] == str(self.object.mailing.pk)][0]
        context['job'] = DjangoJob.objects.get(id=f'send_email_{self.object.mailing.id}')
        context['job_execution'] = [job_execution for job_execution in DjangoJobExecution.objects.all() if
                                    job_execution.job_id == context[
                                        'job'].id]
        context['job_execution_count'] = len(context['job_execution'])
        if len(context['job_execution']) > 0:
            context['job_execution'] = context['job_execution'][0]
        return context


class MailingSettingsDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = MailingSettings

    raise_exception = True

    def test_func(self):
        return self.request.user.is_staff or self.get_object().owner == self.request.user


class MailingPauseView(LoginRequiredMixin, UserPassesTestMixin, View):
    def test_func(self):
        mailing = get_object_or_404(MailingSettings, pk=self.kwargs.get('pk'))
        return self.request.user.is_staff or mailing.owner == self.request.user

    def post(self, request, pk):
        mailing = get_object_or_404(MailingSettings, pk=pk)
        if mailing.mailing_status in ['running', 'created']:
            scheduler.pause_job(job_id=f'send_email_{mailing.pk}')
            mailing.mailing_status = 'completed'
        else:
            scheduler.resume_job(job_id=f'send_email_{mailing.pk}')
            mailing.mailing_status = 'running'
        mailing.save()
        return redirect('mailing_list:mailingsettings_detail', pk=pk)


class StatisticView(LoginRequiredMixin, UserPassesTestMixin, TemplateView):
    template_name = 'mailing_list/statistic.html'

    def test_func(self):
        return self.request.user.is_staff

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['mailing'] = len(MailingSettings.objects.all())
        context['mailing_active'] = len(MailingSettings.objects.exclude(mailing_status='completed'))
        context['clients'] = len(Client.objects.all())
        return context

mailing_list/templates/mailing_list/includes/welcome_message_inc.html
<section class="py-5 text-center container">
    <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto"><h1 class="fw-light">Приветствую тебя!</h1>
            {% if user.is_verify %}
                <p class="lead text-body-secondary">В этом веб приложении ты можешь сделать рассылку, оставить отзыв
                    о
                    нашем сервисе и многое другое!</p>
            {% else %}
                <p class="lead text-body-secondary">Чтобы начать пользоваться приложением пройдите верификацию👋😊 </p>
            {% endif %}
            {% if user.is_verify %}
                <div class="row justify-content-center g-4 mb-4">


                    <div class="col-md-4 d-flex flex-column align-items-center">
                        <a href="{% url 'mailing_list:client_create' %}" class="btn btn-primary w-100 mb-2">
                            Добавить клиента
                        </a>
                        <a href="{% url 'mailing_list:client_list' %}" class="btn btn-outline-primary w-100">
                            Список клиентов
                        </a>
                    </div>


                    <div class="col-md-4 d-flex flex-column align-items-center">
                        <a href="{% url 'mailing_list:message_create' %}" class="btn btn-primary w-100 mb-2">
                            Создать сообщение
                        </a>
                        <a href="{% url 'mailing_list:message_list' %}" class="btn btn-outline-primary w-100 mb-4">
                            Список сообщений
                        </a>
                        {% if perms.users.deactivate_user or user.is_superuser %}
                            <a href="{% url 'users:user_list' %}" class="btn btn-success w-100">
                                Список всех пользователей
                            </a>
                        {% endif %}
                    </div>


                    <div class="col-md-4 d-flex flex-column align-items-center">
                        <a href="{% url 'mailing_list:mailingsettings_create' %}"
                           class="btn btn-primary w-100 mb-2">
                            Создать рассылку
                        </a>
                        <a href="{% url 'mailing_list:mailingsettings_list' %}"
                           class="btn btn-outline-primary w-100">
                            Список рассылок
                        </a>
                    </div>
                </div>

                <section class="py-5 text-center container">
                    <h2 class="text-center  text-body-secondary">Актуальные статьи из нашего блога!</h2>
                    <div class="row justify-content-center mt-4">
                        {% for blog in blog_list %}
                            <div class="col-md-8 mb-3">
                                <div class="card h-100 shadow-sm">
                                    {% if blog.image %}
                                        <img src="{{ blog.image.url }}" class="card-img-top" alt="{{ blog.title }}">
                                    {% endif %}
                                    <div class="card-body">
                                        <h5 class="card-title">{{ blog.title }}</h5>
                                        <a href="{% url 'blog:blog_detail' blog.pk %}"
                                           class="btn btn-outline-primary mt-3 align-self-start">
                                            Подробнее
                                        </a>
                                    </div>
                                </div>
                            </div>
                        {% empty %}
                            <div class="col-12">
                                <div class="alert alert-info text-center">
                                    Блоги не найдены
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </section>
            {% endif %}
        </div>
    </div>
</section>