blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView

app_name = BlogConfig.name

urlpatterns = [
    path('blog_create', BlogCreateView.as_view(), name='blog_create'),
    path('blog_list', BlogListView.as_view(), name='blog_list'),
    path('blog_detail/<int:pk>', BlogDetailView.as_view(), name='blog_detail')
]

mailing_list/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mailing_list.apps import MailingListConfig
from mailing_list.views import ClientCreateView, MessageCreateView, MailingSettingsCreateView, HomeView, ClientListView, \
    ClientDetailView, ClientDeleteView, MessageListView, MessageDetailView, MessageDeleteView, MailingSettingsListView, \
    MailingSettingsDetailView, MailingSettingsDeleteView, ClientUpdateView, MailingAttemptDetailView, MailingPauseView, \
    StatisticView

app_name = MailingListConfig.name
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('client_create', ClientCreateView.as_view(), name='client_create'),
    path('message_create', MessageCreateView.as_view(), name='message_create'),
    path('mailingsettings_create', MailingSettingsCreateView.as_view(), name='mailingsettings_create'),

    path('client_list', ClientListView.as_view(), name='client_list'),
    path('client_detail/<int:pk>', ClientDetailView.as_view(), name='client_detail'),
    path('client_detail/<int:pk>/delete', ClientDeleteView.as_view(), name='client_delete'),
    path('client_detail/<int:pk>/update', ClientUpdateView.as_view(), name='client_update'),

    path('message_list', MessageListView.as_view(), name='message_list'),
    path('message_detail/<int:pk>', MessageDetailView.as_view(), name='message_detail'),
    path('message_detail/<int:pk>/delete', MessageDeleteView.as_view(), name='message_delete'),
    path('mailingsettings_list', MailingSettingsListView.as_view(), name='mailingsettings_list'),
    path('mailingsettings_detail/<int:pk>', MailingSettingsDetailView.as_view(), name='mailingsettings_detail'),
    path('mailingsettings_detail/<int:pk>/delete', MailingSettingsDeleteView.as_view(), name='mailingsettings_delete'),
    path('mailingsettings_detail/attempt/<str:slug>', MailingAttemptDetailView.as_view(), name='mailingsettings_attempt'),
    path('mailing_pause/<int:pk>', MailingPauseView.as_view(), name='mailing_pause'),
    path('statistic/', StatisticView.as_view(), name='statistic'),

]

scheduler_email/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from scheduler_email import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('mailing_list.urls', namespace='mailing_list')),
                  path('', include('users.urls', namespace='users')),
                  path('blog/', include('blog.urls', namespace='blog'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from django.views.decorators.cache import cache_page

from users.apps import UsersConfig
from users.forms import LoginForm
from users.views import UserRegisterView, UserInputSecretKey, UserListView, UserDeactivateView

app_name = UsersConfig.name

urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='user_register'),
    path('login/', LoginView.as_view(template_name='users/user_login.html', form_class=LoginForm), name='user_login'),
    path('logout/', LogoutView.as_view(), name='user_logout'),
    path('user_verify/<int:pk>', UserInputSecretKey.as_view(), name='user_verify'),
    path('user_list', UserListView.as_view(), name='user_list'),
    path('user_deactivate/<int:pk>', UserDeactivateView.as_view(), name='user_deactivate'),
]

mailing_list/models.py
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import post_save
from slugify import slugify

from scheduler_email.settings import AUTH_USER_MODEL
from users.models import User

NULLABLE = {'blank': True, 'null': True}


class Client(models.Model):
    mail = models.EmailField(max_length=100, verbose_name='почта')
    fullname = models.CharField(max_length=200, verbose_name='полное имя')
    comment = models.TextField(verbose_name='комментарий')
    owner = models.ForeignKey(AUTH_USER_MODEL, default=True, on_delete=models.CASCADE, to_field='id', verbose_name='Пользователь', **NULLABLE)

    def __str__(self):
        return self.fullname

    class Meta:
        verbose_name = 'клиент'
        verbose_name_plural = 'клиенты'


class Message(models.Model):
    title_message = models.CharField(max_length=200, verbose_name='тема письма')
    body_message = models.TextField(verbose_name='тело письма')
    owner = models.ForeignKey(AUTH_USER_MODEL, default=True, on_delete=models.CASCADE, to_field='id', verbose_name='Пользователь', **NULLABLE)

    def __str__(self):
        return self.title_message

    class Meta:
        verbose_name = 'сообщение для рассылки'
        verbose_name_plural = 'сообщения для рассылки'


class MailingSettings(models.Model):
    title = models.CharField(max_length=200, default='', verbose_name='Название рассылки')
    first_sending_date = models.DateTimeField(verbose_name='дата и время первой отправки рассылки')
    period = models.PositiveSmallIntegerField(verbose_name='периодичность')
    mailing_status = models.CharField(default=False, choices=[
        ('created', 'Создана'),
        ('running', 'Активна'),
        ('completed', 'Завершена')], verbose_name='статус')
    message = models.ForeignKey(Message, default=None, on_delete=models.CASCADE, to_field='id',
                                verbose_name='сообщение')
    client = models.ManyToManyField(Client, default=None, related_name='mailing', verbose_name='клиент')
    owner = models.ForeignKey(AUTH_USER_MODEL, default=True, related_name='mailing', on_delete=models.CASCADE, to_field='id', verbose_name='Пользователь', **NULLABLE)

    # day='*/10' → каждые 10 дней

    def __str__(self):
        return f'{self.first_sending_date, self.period, self.mailing_status}'

    class Meta:
        verbose_name = 'настройка рассылки'
        verbose_name_plural = 'настройки рассылки'


class MailingAttempt(models.Model):
    mailing = models.OneToOneField(MailingSettings, default=False, on_delete=models.CASCADE, related_name='log',
                                   verbose_name='рассылка')
    slug = models.SlugField(max_length=200, unique=True, blank=True, verbose_name='URL slug')
    last_attempt_date = models.DateTimeField(**NULLABLE, verbose_name='дата и время последней попытки')
    attempt_status = models.BooleanField(**NULLABLE, default=False, verbose_name='статус попытки')
    mail_service_response = models.TextField(**NULLABLE, default=None, verbose_name='ответ почтового сервиса')
    owner = models.ForeignKey(AUTH_USER_MODEL, default=True, on_delete=models.CASCADE, to_field='id', verbose_name='Пользователь', **NULLABLE)

    def __str__(self):
        return f'{self.attempt_status}, {self.last_attempt_date}, {self.mail_service_response}'

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.mailing.title)
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'попытка рассылки'
        verbose_name_plural = 'попытки рассылки'


@receiver(post_save, sender=MailingSettings)
def create_mailing_log(sender, instance, created, **kwargs):
    if created:
        MailingAttempt.objects.create(mailing=instance, owner=instance.owner)

mailing_list/forms.py
from django import forms

from mailing_list.models import Client, Message, MailingSettings


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ClientForm(StyleFormMixin, forms.ModelForm ):
    class Meta:
        model = Client
        fields = '__all__'

class MessageForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Message
        fields = '__all__'

class MailingSettingsForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = MailingSettings
        fields = ('title', 'first_sending_date', 'period', 'mailing_status', 'message', 'client')

mailing_list/views.py
from apscheduler.triggers.cron import CronTrigger
from apscheduler.triggers.interval import IntervalTrigger
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import ListView, CreateView, TemplateView, DetailView, DeleteView, UpdateView
from django_apscheduler.models import DjangoJobExecution, DjangoJob

from blog.models import Blog
from mailing_list.forms import ClientForm, MessageForm, MailingSettingsForm
from mailing_list.management.commands.logger import logger
from mailing_list.models import Client, Message, MailingSettings, MailingAttempt
from dj_scheduler import scheduler, send_email_to_clients
from mailing_list.services import get_cached_queryset


class SelfUserPassesTestMixin(UserPassesTestMixin):
    """Чтобы придерживаться принципа DRY"""
    raise_exception = True

    def test_func(self):
        return self.request.user.is_superuser or self.get_object().owner == self.request.user


class HomeView(LoginRequiredMixin, TemplateView):
    template_name = 'mailing_list/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['blog_list'] = Blog.objects.order_by('-publish_date')[:3]
        return context


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mailing_list:client_list')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class ClientListView(LoginRequiredMixin, ListView):
    model = Client

    def get_queryset(self):
        print(self.request.user.pk)
        return get_cached_queryset(self.request.user, Client)


class ClientDetailView(LoginRequiredMixin, SelfUserPassesTestMixin, DetailView):
    model = Client


class ClientDeleteView(LoginRequiredMixin, SelfUserPassesTestMixin, DeleteView):
    model = Client
    success_url = reverse_lazy('mailing_list:client_list')


class ClientUpdateView(LoginRequiredMixin, SelfUserPassesTestMixin, UpdateView):
    model = Client
    form_class = ClientForm

    def get_success_url(self):
        return reverse('mailing_list:client_detail', kwargs={'pk': self.object.pk})


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('mailing_list:message_list')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class MessageListView(LoginRequiredMixin, ListView):
    model = Message

    def get_queryset(self):
        return get_cached_queryset(self.request.user, Message)


class MessageDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = Message
    raise_exception = True

    def test_func(self):
        return self.request.user.is_staff or self.get_object().owner == self.request.user


class MessageDeleteView(LoginRequiredMixin, SelfUserPassesTestMixin, DeleteView):
    model = Message
    success_url = reverse_lazy('mailing_list:message_list')


class MailingSettingsCreateView(LoginRequiredMixin, CreateView):
    model = MailingSettings
    form_class = MailingSettingsForm
    success_url = reverse_lazy('mailing_list:mailingsettings_list')

    def form_valid(self, form):
        if form.is_valid():
            form.instance.owner = self.request.user
            mailing_settings = form.save()
            logger.info(f'{mailing_settings.first_sending_date}')
            scheduler.add_job(
                send_email_to_clients,
                trigger=IntervalTrigger(days=mailing_settings.period,
                                        start_date=mailing_settings.first_sending_date),
                id=f'send_email_{mailing_settings.id}',
                max_instances=1,
                replace_existing=True,

                kwargs={'message_id': mailing_settings.message.id, 'mailing_id': mailing_settings.id}
            )
            logger.info('джоба добавлена')
            mailing_settings.save()
        return super().form_valid(form)


class MailingSettingsListView(LoginRequiredMixin, ListView):
    model = MailingSettings

    def get_queryset(self):
        return get_cached_queryset(self.request.user, MailingSettings)


class MailingSettingsDeleteView(LoginRequiredMixin, SelfUserPassesTestMixin, DeleteView):
    model = MailingSettings

    def get_success_url(self):
        scheduler.remove_job(f'send_email_{self.object.pk}')
        return reverse_lazy('mailing_list:mailingsettings_list')


class MailingAttemptDetailView(LoginRequiredMixin, SelfUserPassesTestMixin, DetailView):
    model = MailingAttempt
    slug_field = 'slug'
    slug_url_kwarg = 'slug'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['job'] = [job for job in DjangoJob.objects.all() if job.id[-1:] == str(self.object.mailing.pk)][0]
        context['job'] = DjangoJob.objects.get(id=f'send_email_{self.object.mailing.id}')
        context['job_execution'] = [job_execution for job_execution in DjangoJobExecution.objects.all() if
                                    job_execution.job_id == context[
                                        'job'].id]
        context['job_execution_count'] = len(context['job_execution'])
        if len(context['job_execution']) > 0:
            context['job_execution'] = context['job_execution'][0]
        return context


class MailingSettingsDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = MailingSettings

    raise_exception = True

    def test_func(self):
        return self.request.user.is_staff or self.get_object().owner == self.request.user


class MailingPauseView(LoginRequiredMixin, UserPassesTestMixin, View):
    def test_func(self):
        mailing = get_object_or_404(MailingSettings, pk=self.kwargs.get('pk'))
        return self.request.user.is_staff or mailing.owner == self.request.user

    def post(self, request, pk):
        mailing = get_object_or_404(MailingSettings, pk=pk)
        if mailing.mailing_status in ['running', 'created']:
            scheduler.pause_job(job_id=f'send_email_{mailing.pk}')
            mailing.mailing_status = 'completed'
        else:
            scheduler.resume_job(job_id=f'send_email_{mailing.pk}')
            mailing.mailing_status = 'running'
        mailing.save()
        return redirect('mailing_list:mailingsettings_detail', pk=pk)


class StatisticView(LoginRequiredMixin, UserPassesTestMixin, TemplateView):
    template_name = 'mailing_list/statistic.html'

    def test_func(self):
        return self.request.user.is_staff

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['mailing'] = len(MailingSettings.objects.all())
        context['mailing_active'] = len(MailingSettings.objects.exclude(mailing_status='completed'))
        context['clients'] = len(Client.objects.all())
        return context

mailing_list/templates/mailing_list/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" data-bs-theme="auto">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Планировщик рассылок</title>

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
{% if messages %}
    <div class="toast-container position-fixed bottom-0 end-0 p-3">
        {% for message in messages %}
            <div class="toast align-items-center text-bg-dark border-0 mb-2"
                 role="alert"
                 aria-live="assertive"
                 aria-atomic="true"
                 data-bs-delay="5000"
                 data-bs-autohide="true">

                <div class="d-flex">
                    <div class="toast-body">
                        {{ message }}
                    </div>
                    <button type="button"
                            class="btn-close btn-close-white me-2 m-auto"
                            data-bs-dismiss="toast">
                    </button>
                </div>
            </div>
        {% endfor %}
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const toastElList = document.querySelectorAll('.toast')
            const toastList = [...toastElList].map(toastEl => new bootstrap.Toast(toastEl).show())
        });
    </script>
{% endif %}
<body>
<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
    <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"></path>
    </symbol>
    <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"></path>
    </symbol>
    <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"></path>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"></path>
    </symbol>
    <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"></path>
    </symbol>
</svg>
<header data-bs-theme="dark">
    <div class="collapse text-bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4"><h4>О нас</h4>
                    <p class="text-body-secondary">В этом приложении вы можете заказать рассылку вашей информации.</p>
                </div>
                <div class="col-sm-4 offset-md-1 py-4"><h4>Инфо</h4>
                    <ul class="list-unstyled">
                        {% if user.is_authenticated %}
                            <li><a href="#" class="text-white">{{ user.email }}</a></li>
                        {% endif %}
                        {% if user.is_staff %}
                            <li><a href="{% url 'mailing_list:statistic' %}" class="text-white">Статистика</a></li>
                        {% endif %}
                        <li><a href="https://t.me/levimachine" class="text-white">Наш телеграмм</a></li>
                        <li><a href="{% url 'blog:blog_list' %}" class="text-white">Блог</a></li>
                        {% if not user.is_authenticated %}
                            <li><a href="{% url 'users:user_register' %}" class="text-white">Регистрация</a></li>
                            <li><a href="{% url 'users:user_login' %}" class="text-white">Логин</a></li>
                        {% else %}
                            {% if not user.is_verify %}
                                <li><a href="{% url 'users:user_verify' user.pk %}" class="text-white">Верификация</a>
                                </li>
                            {% endif %}
                            <li>
                                <form action="{% url 'users:user_logout' %}" method="post" class="inline">
                                    {% csrf_token %}
                                    <button
                                            type="submit"
                                            class="text-white bg-transparent border-0 p-0 cursor-pointer"
                                            style="text-decoration: underline;"
                                    >
                                        Выйти
                                    </button>
                                </form>
                            </li>

                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container"><a href="{% url 'mailing_list:home' %}" class="navbar-brand d-flex align-items-center">
            <strong>Рассылка сообщений</strong> </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation"><span
                    class="navbar-toggler-icon"></span></button>
        </div>
    </div>
</header>

{% block content %}
{% endblock %}

<footer>
    <div class="container">
        <footer class="py-3 my-4">
            <ul class="nav justify-content-center border-bottom pb-3 mb-3">
                <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Home</a></li>
                <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Features</a></li>
                <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Pricing</a></li>
                <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">FAQs</a></li>
                <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">About</a></li>
            </ul>
            <p class="text-center text-body-secondary">© 2025 Company, Inc</p></footer>
    </div>
</footer>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

mailing_list/templates/mailing_list/client_form.html
{% extends 'mailing_list/base.html' %}

{% block content %}
    <br>
    <br>
    <h1>Создание клиента для рассылки</h1>
    <br>
    <br>
    <div class="card centered">
        <div class="container centered">
            <form method="post">
                {% csrf_token %}

                <div class="mb-3">
                    <label for="id_mail" class="form-label">Email адрес</label>
                    {{ form.mail }}
                </div>
                <div class="mb-3">
                    <label for="id_fullname" class="form-label">Полное имя</label>
                    {{ form.fullname }}
                </div>
                <div class="mb-3">
                    <label for="id_comment" class="form-label">Комментарий</label>
                    {{ form.comment }}
                </div>
                {% if object %}
                    <button type="submit" class="btn btn-success my-2">
                        Редактировать
                    </button>
                {% else %}
                    <button type="submit" class="btn btn-primary my-2">
                        Создать
                    </button>
                {% endif %}
            </form>
        </div>
    </div>

{% endblock %}

mailing_list/templates/mailing_list/mailingsettings_detail.html
{% extends 'mailing_list/base.html' %}

{% block content %}
    <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3"><h4 class="my-0 fw-normal">{{ mailingsettings.title }}</h4></div>
            <ul class="list-unstyled mt-3 mb-4">
                <li><p>1. Id рассылки - {{ mailingsettings.pk }}</p></li>
                <li><p>2. Список получателей -
                    {% for element in mailingsettings.client.all %}
                        {{ element }},
                    {% endfor %}
                </p></li>
                <li><p>3. Периодичность(в днях) - {{ mailingsettings.period }}</p></li>
                <li><p>4. Старт рассылки - {{ mailingsettings.first_sending_date }}</p></li>
                <li><p>5. Название сообщения - {{ mailingsettings.message.title_message }}</p></li>
            </ul>
            <a type="button" href="{% url 'mailing_list:mailingsettings_list' %}" class="w-100 btn btn-lg btn-primary">К
                списку
                рассылок</a>
            <a type="button"
               href="{% url 'mailing_list:mailingsettings_attempt' mailingsettings.log.slug %}"
               class="w-100 btn btn-lg btn-info text-white">Логи рассылки</a>
            <form method="post" action="{% url 'mailing_list:mailing_pause' mailingsettings.pk %}" class="w-100">
                {% csrf_token %}
                <button type="submit"
                        class="w-100 btn btn-lg btn-{% if mailingsettings.mailing_status == 'running' or mailingsettings.mailing_status == 'created' %}warning{% else %}success{% endif %} text-white">
                    {% if mailingsettings.mailing_status == 'running' or mailingsettings.mailing_status == 'created' %}
                        Выключить рассылку{% else %}Включить рассылку{% endif %}
                </button>
            </form>
            <a type="button" href="{% url 'mailing_list:mailingsettings_delete' mailingsettings.pk %}"
               class="w-100 btn btn-lg btn-danger">Удалить рассылку</a>
        </div>
    </div>
{% endblock %}

mailing_list/templates/mailing_list/mailingsettings_form.html
{% extends 'mailing_list/base.html' %}

{% block content %}
    <br>
    <br>
    <h1>Создание рассылки</h1>
    <br>
    <br>

    <div class="card centered">
        <div class="container centered">
            <form method="post">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="id_title" class="form-label">Название рассылки</label>
                    {{ form.title }}
                </div>
                <div class="mb-3">
                    <label for="id_first_sending_date" class="form-label">Дата и время первой отправки</label>
                    <input
                            type="datetime-local"
                            name="first_sending_date"
                            id="id_first_sending_date"
                            class="form-control"
                            required
                    >
                </div>

                <div class="mb-3">
                    <label for="id_period" class="form-label">Периодичность (в днях), каждые</label>
                    {{ form.period }} дней
                </div>

                <div class="mb-3">
                    <label for="id_mailing_status" class="form-label">Статус</label>
                    {{ form.mailing_status }}
                </div>

                <div class="mb-3">
                    <label for="id_message" class="form-label">Сообщение</label>
                    {{ form.message }}
                </div>
                <div class="mb-3">
                    <label for="id_client" class="form-label">Клиенты</label>
                    {{ form.client }}
                </div>
                <button type="submit" class="btn btn-primary my-2">Создать
                </button>
            </form>
        </div>
    </div>
{% endblock %}

mailing_list/templates/mailing_list/message_list.html
{% extends 'mailing_list/base.html' %}

{% block content %}
    <br>
    <br>
    <h1>Список сообщений</h1>
    <br>
    <br>
    {% for message in message_list %}
        <div class="col">
            <div class="card mb-4 rounded-3 shadow-sm">
                <div class="card-header py-3"><h4 class="my-0 fw-normal">{{ message.title_message }}</h4></div>
                <a type="button" href="{% url 'mailing_list:message_detail' message.pk %}"
                   class="w-100 btn btn-lg btn-outline-primary">Подробнее</a>
            </div>
        </div>
    {% endfor %}
{% endblock %}