blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView

app_name = BlogConfig.name

urlpatterns = [
    path('blog_create', BlogCreateView.as_view(), name='blog_create'),
    path('blog_list', BlogListView.as_view(), name='blog_list'),
    path('blog_detail/<int:pk>', BlogDetailView.as_view(), name='blog_detail')
]

mailing_list/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mailing_list.apps import MailingListConfig
from mailing_list.views import ClientCreateView, MessageCreateView, MailingSettingsCreateView, HomeView, ClientListView, \
    ClientDetailView, ClientDeleteView, MessageListView, MessageDetailView, MessageDeleteView, MailingSettingsListView, \
    MailingSettingsDetailView, MailingSettingsDeleteView, ClientUpdateView, MailingAttemptDetailView, MailingPauseView, \
    StatisticView

app_name = MailingListConfig.name
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('client_create', ClientCreateView.as_view(), name='client_create'),
    path('message_create', MessageCreateView.as_view(), name='message_create'),
    path('mailingsettings_create', MailingSettingsCreateView.as_view(), name='mailingsettings_create'),

    path('client_list', ClientListView.as_view(), name='client_list'),
    path('client_detail/<int:pk>', ClientDetailView.as_view(), name='client_detail'),
    path('client_detail/<int:pk>/delete', ClientDeleteView.as_view(), name='client_delete'),
    path('client_detail/<int:pk>/update', ClientUpdateView.as_view(), name='client_update'),

    path('message_list', MessageListView.as_view(), name='message_list'),
    path('message_detail/<int:pk>', MessageDetailView.as_view(), name='message_detail'),
    path('message_detail/<int:pk>/delete', MessageDeleteView.as_view(), name='message_delete'),
    path('mailingsettings_list', MailingSettingsListView.as_view(), name='mailingsettings_list'),
    path('mailingsettings_detail/<int:pk>', MailingSettingsDetailView.as_view(), name='mailingsettings_detail'),
    path('mailingsettings_detail/<int:pk>/delete', MailingSettingsDeleteView.as_view(), name='mailingsettings_delete'),
    path('mailingsettings_detail/attempt/<str:slug>', MailingAttemptDetailView.as_view(), name='mailingsettings_attempt'),
    path('mailing_pause/<int:pk>', MailingPauseView.as_view(), name='mailing_pause'),
    path('statistic/', StatisticView.as_view(), name='statistic'),

]

scheduler_email/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from scheduler_email import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('mailing_list.urls', namespace='mailing_list')),
                  path('', include('users.urls', namespace='users')),
                  path('blog/', include('blog.urls', namespace='blog'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Blog(models.Model):
    title = models.CharField(max_length=200, verbose_name='Заголовок')
    content = models.TextField(verbose_name='Содержание статьи')
    image = models.ImageField(upload_to='blog/', verbose_name='Изображение')
    views_count = models.IntegerField(default=0, verbose_name='Количество просмотров', blank=True, null=True)
    publish_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'блог'
        verbose_name_plural = 'блоги'

blog/forms.py
from django import forms

from blog.models import Blog
from mailing_list.forms import StyleFormMixin


class BlogForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Blog
        fields = ('title', 'content', 'image' )

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView
from blog.services import get_cached_queryset
from blog.forms import BlogForm
from blog.models import Blog


class BlogCreateView(LoginRequiredMixin,UserPassesTestMixin,  CreateView):
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy('blog:blog_list')
    raise_exception = True

    def test_func(self):
        return self.request.user.has_perm('blog.add_blog')


class BlogListView(LoginRequiredMixin, ListView):
    model = Blog


    def get_queryset(self):
        return get_cached_queryset()



class BlogDetailView(LoginRequiredMixin, DetailView):
    model = Blog

    def get_object(self, queryset=None):
        blog = super().get_object(queryset)
        if self.request.user.is_staff:
            return blog
        else:
            blog.views_count += 1
            blog.save()
            return blog

blog/templates/blog/blog_detail.html
{% extends 'mailing_list/base.html' %}

{% block content %}
    <section class="py-5 container">
    <div class="row justify-content-center">
        <div class="col-lg-8 col-md-10">
            <!-- Карточка блога -->
            <div class="card shadow-sm mb-4">
                {% if blog.image %}
                    <img src="{{ blog.image.url }}" class="card-img-top" alt="{{ blog.title }}">
                {% endif %}
                <div class="card-body">
                    <h1 class="card-title mb-3">{{ blog.title }}</h1>
                    <p class="text-muted mb-2">
                        Опубликовано: {{ blog.publish_date }} | Просмотры: {{ blog.views_count }}
                    </p>
                    <hr>
                    <div class="card-text mb-4">
                        {{ blog.content|linebreaks }}
                    </div>
                    <a href="{% url 'blog:blog_list' %}" class="btn btn-outline-primary">К списку блогов
                    </a>
                    <a href="{% url 'mailing_list:home' %}" class="btn btn-outline-success">На главную
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'mailing_list/base.html' %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Создать</button>
    </form>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'mailing_list/base.html' %}

{% block content %}
    <section class="py-5 text-center container">
        {% if perms.blog.add_blog %}
            <div class="row py-lg-5 justify-content-center">
                <div class="col-md-4 d-flex flex-column align-items-center">
                    <a href="{% url 'blog:blog_create' %}" class="btn btn-primary w-100 mb-4 btn-lg">
                        Создать блог
                    </a>
                </div>
            </div>
        {% endif %}

        <div class="row justify-content-center mt-4">
            {% for blog in blog_list %}
                <div class="col-md-7 mb-3">
                    <div class="card h-100 shadow-sm">
                        {% if blog.image %}
                            <img src="{{ blog.image.url }}" class="card-img-top" alt="{{ blog.title }}">
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title">{{ blog.title }}</h5>
                            <a href="{% url 'blog:blog_detail' blog.pk %}"
                           class="btn btn-outline-primary mt-3 align-self-start">
                            Подробнее
                        </a>
                        </div>
                    </div>
                </div>
            {% empty %}
                <div class="col-12">
                    <div class="alert alert-info text-center">
                        Блоги не найдены
                    </div>
                </div>
            {% endfor %}
        </div>
    </section>
{% endblock %}